package models;

public class ResultatModel {
    private int ResultatID;
    private int AtletID;
    private int Rank;
    private char Score;
    private int 3KMSekund;
    private String 3KMTid;
    private int 5KMWatt;
    private String 5KMTid;
    private int 2KMWatt;
    private String 2KMTid;
    private int 60TestIWatt;
    private char LiggRoProsent;
    private int LiggRoKg;
    private int KnebøyProsent;
    private char KnebøyKg;
    private int Bevegelighet;
    private char Kroppshev;
    private char Sargeant;
    private int Uke;
    private int År;

    public ResultatModel(int KlasseID, String KlasseNavn) {
        this.ResultatIDID = ResultatID;
        this.AtletID = AtletID;
        this.Rank = Rank;
        this.Score = Score;
        this.3KMSekund = 3KMSekund;